### ISSUE TITLE
Support for Additional Eyeglass Module Search Paths (such as bower_components)

### ISSUE THREAD

**Issue by kohlmannj** [sass-eyeglass/eyeglass#125]
Hi all,

I'm not sure this is even a great suggestion, but for purposes of, say, decoupling an Eyeglass-aware build engine (with one set of packages) from a project-specific folder of resources (perhaps with its own set of packages), it'd be great if there were an option to have Eyeglass search for modules within additional directories.

As mentioned in the title, this might also support approaches to search in other package managers' folders, such as `bower_components` et al.

**Comment by eoneill** [comment]
Related to #96

**Comment by chriseppstein** [comment]
I just closed #96. We're not going to support other module distribution systems. It erodes the value of the Sass ecosystem because you cannot have interdependencies between different module systems. I'm sure someone can write a bower importer for node-sass just like we wrote one for npm. Eyeglass will interoperate with that due to the simple fact that we support the node-sass `importer` option.

**Comment by kohlmannj** [comment]
Good call, honestly. I'll add that since I posted this, I ended up getting my core Sass libraries out of Bower and back into NPM. I'm doing Bower integration by way of adding `bower_components` to the Sass compiler's include paths.

(Currently this is most important for loading single Sass files for components, rather than whole Sass libraries residing in `bower_components`, so it works out. )
