### ISSUE TITLE
bower support?

### ISSUE THREAD

**Issue by chriseppstein** [sass-eyeglass/eyeglass#14]
Does it make sense to try to support other package managers in eyeglass like bower?

**Comment by Jakobo** [comment]
We should add #religion to this tag. So, what follows is really personal opinion. 

**there are too many package managers** That doesn't mean we should / shouldn't support Bower. But we must exercise caution in chasing NuGet, jspm.io, Bower, etc. Each one requires is own JSON file, release process, etc. To keep eyeglass light and simple, we should keep the total number of these down intentionally. 

**Bower, deduping, and eyeglass modules** I actually appreciate their module resolution system. It is more in line with ruby, on which Sass was based (global resolution, one version of things). However, Bower was intended for client side components. For pure Sass modules, supporting Bower may be a good idea. For supporting custom functions, however, it seems unwise to put node.js code into Bower. I'm not convinced we get a lot of gain here for the headache of having people search two different ecosystems for eyeglass modules. (once npm has ecosystems, finding eyeglass stuff will be even easier)

I'd prefer to hold off for now, especially since we are just trying to build the 1.0. :)

**Comment by scottdavis** [comment]
Our setup at work uses bower and npm I've enjoyed bower because it just seems to work so I'm a +1 for bower

**Comment by chriseppstein** [comment]
Agree that this shouldn't be part of the 1.0 release if we decide it's a
good idea.

**Comment by Jakobo** [comment]
Once [npm implements ecosystems](http://blog.npmjs.org/post/94662089625/the-future-of-the-npm-website-lets-map-this) this may become a non-issue. In the meantime, people who want to get bower-like functionality may be interested in using [npm dedupe](https://docs.npmjs.com/cli/dedupe) to preemptively resolve potential conflicts before running eyeglass.

**Comment by chriseppstein** [comment]
consensus seems to be that we should only support npm for the foreseeable future.

**Comment by kaelig** [comment]
I'm currently looking at how we (Financial Times) could leverage eyeglass to load our [Origami](http://origami.ft.com) modules and our whole architecture works on top of a private Bower registry… We're not going to use npm anytime soon (we're waiting to see what npm v3 offers) because Bower works really well for us.

I'd love to see eyeglass work with Bower out of the box. I gave it a shot but my NodeJS isn't that good.

**Comment by kaelig** [comment]
Also, think about looking towards browserify + debowerify to ease the process. I'm no expert but it's worked well for me in the past.
