### ISSUE TITLE
Different main file than index.scss

### ISSUE THREAD

**Issue by strarsis** [sass-eyeglass/eyeglass#166]
Sometimes in sass projects without eyeglass support yet, the main file is named differently than index.scss.
How can I declare a different file than index.scss to be the main file eyeglass should import when the eyeglass package is imported?

Example in recent PR: https://github.com/hudochenkov/sass-text-stroke/pull/1/files

**Comment by eoneill** [comment]
Unfortunately, you can't configure this. Eyeglass resolves import paths by naming convention. See [NameExpander.js](https://github.com/sass-eyeglass/eyeglass/blob/master/lib/util/NameExpander.js) for the current logic around this. The only thing you can configure is the root Sass directory (`sassDir`).

**Comment by ArmorDarks** [comment]
Why not use `package.json` `main` property for this? It quite standard expectation to work this way.

**Comment by strarsis** [comment]
@ArmorDarks: It doesn't seem to work in this case (https://github.com/hudochenkov/sass-text-stroke/pull/1/files). Remove the index.scss in that PR and use main field in package.json - @importing it will fail.

**Comment by ArmorDarks** [comment]
@strarsis Yes, I know. That question has been addressed to @eoneill

**Comment by strarsis** [comment]
@ArmorDarks: Yes, the main field is ideal for this. You should open a new issue for adding support of main field.

**Comment by eoneill** [comment]
Some context: when we initially created eyeglass, we evaluated a lot of existing sass modules on bower and npm. Overwhelmingly, the pattern was that `package.json#main` pointed to a javascript file. We leveraged this convention so that when eyeglass does a `require('my-sass-module')`, it receives a function that will configure your module for eyeglass. As this is a node/npm convention, it did not seem fit to overload this behavior with a sass entry point. Instead, we follow a standard naming convention to resolve file imports.

That said, in the above example PR, you could have removed the `index.scss` file in favor of using the existing named `_text-stroke.scss` file. You would just change your `package.json#eyeglass` config to look something like this:
```
"eyeglass": {
  "name": "text-stroke",
  ...
}
```

Eyeglass will then correctly find `_text-stroke.scss` (by above mentioned naming convention) when a consuming scss file does an `@import "text-stroke";`. This would better align with consumers who are already using the package as they would not have to change their imports to `sass-text-stroke`.

**Comment by strarsis** [comment]
@eoneill: Would using the main field in package.json instead remove a bit redundancy?

**Comment by ArmorDarks** [comment]
@eoneill thanks for detailed explanation!

However, I still do not understand completely why exactly that solution was taken.

For instance, we know that `package.json` can contain four variants:

1. `main: 'myFIle.scss` / main: 'myFIle.sass` / main: 'myFIle.css`
2. `main: 'myFIle.js`
3. `main: 'myFIle.SOMEunknownEXT`

We can adjust based on extension.

In 1st case we definitely have to use `main` in first place as entry point, since by examin extensions we can be sure that it is truly Sass files. We can use them.

In 3nd case it seems to be js, based on extension, and we can act accordingly.

3rd case obviously can be ignored, Eyeglass should fallback to it's current default mechanism of locating entry point.

> Some context: when we initially created eyeglass, we evaluated a lot of existing sass modules on bower and npm. Overwhelmingly, the pattern was that package.json#main pointed to a javascript file.

Nobody used Sass or CSS files as `main` simply because there were no practical reason behind. Tools like Eyeglass had to create precedent and make it practical, thus helping people to return on right track. Still, it isn't late to do that.

**Comment by eoneill** [comment]
Another reason we did not use `main` as the entry point is because eyeglass needs a `sassDir` path to correctly resolve imports.

For example, if you're directory structure looked like...
```scss
foo
└── sass
    ├── bar.scss
    └── index.scss
```

and your `package.json` declared:
```js
"eyeglass": {
  // ...
  "sassDir": "./sass/"
}
```

`main` is now ambiguous, would it be `index.scss` or `sass/index.scss`?

Because of this and the above mentioned reasons, we prefer convention over configuration here and don't see a need to change this at this point.

**Comment by strarsis** [comment]
@eoneill: I adjusted the package.json of that eyeglass module accordingly (in an extra branch, see https://github.com/hudochenkov/sass-text-stroke/blob/eyeglass-test/package.json) - but sass can't import it using `@import 'text-stroke';`:
````
$ npm install --save-dev github:hudochenkov/sass-text-stroke#test-eyeglass
````
````
$ gulp styles
[...]
text-stroke
Error: Failed to load SCSS include: text-stroke
        on line 1 of text-stroke
>> @error "Failed to load SCSS include: text-stroke"
````

**Comment by eoneill** [comment]
It looks like this commit removed the `sassDir` https://github.com/hudochenkov/sass-text-stroke/commit/808316de20549b26df9606f07d09c7af843aba37

Your eyeglass config should be:
```json
"eyeglass": {
  "name": "text-stroke",
  "sassDir": "./",
  "needs": "*",
  "exports": false
}
```

**Comment by strarsis** [comment]
@eoneill: That was it, thanks!

**Comment by ArmorDarks** [comment]
> Another reason we did not use main as the entry point is because eyeglass needs a sassDir path to correctly resolve imports.

Why not use path from `main` for finding that path?

```
main: ./sass/myFIle.scss'
```

Extraction of path from it is quite trivial.

> Because of this and the above mentioned reasons, we prefer convention over configuration here and don't see a need to change this at this point.

It's more looks like a deviation from already established standard. Yeap, it's Node standard, but we're using Node's `package.json` after all.
