### ISSUE TITLE
use es6 for development?

### ISSUE THREAD

**Issue by chriseppstein** [sass-eyeglass/eyeglass#28]
ES6 is pretty nice. Any objections to using it for development of eyeglass modules and transpiling it down?

**Comment by Jakobo** [comment]
Only that it's compile-down. It'd be nice if `--harmony` didn't have to happen :) No objection here.

The best tool in the business IMO Babel has this to say though: https://babeljs.io/docs/using-babel/

> Not suitable for libraries
> The require hook automatically hooks itself into all node requires. This will pollute the global scope and introduce conflicts. Because of this it's not suitable for libraries, if however you're writing an application then it's completely fine to use.

Any other transpilers come to mind?

**Comment by acdlite** [comment]
Babel works great for libs — it's only the `require` hook that you need to avoid.

What I do is I have a `src/` folder with ES6 files, which is transpiled to a `lib/` folder. The `main` field of `package.json` is `lib/whatever.js`. `lib/` can be added to .gitignore. (You'll also need to add a separate `.npmignore` file so that `lib/` isn't ignored when publishing to npm — otherwise `.gitignore` is used by default). As a final step, add a `prepublish` script to `package.json` that transpiles before publishing.

If it helps, you can reference this project of mine, which uses this setup: https://github.com/acdlite/flummox/blob/master/CONTRIBUTING.md#file-organization

**Comment by acdlite** [comment]
To clarify further, the require hook is an optional feature of Babel that lets you require ES6 files and transpile them on the fly. The warning about libraries applies only to the hook, not to Babel itself.

**Comment by chriseppstein** [comment]
I think babel can be used as just a transpiler in gulp and not hooked into require.

**Comment by Jakobo** [comment]
That's great news. I'm all for es6 today. :)

**Comment by HugoGiraudel** [comment]
We use Babel at SassDoc and are very happy with it. :)

**Comment by Jakobo** [comment]
Any followup on this? Here's the items as I see them

1. Need to add a `gulp compile` step or equivalent, probably using Babel
2. Need to add a `gulp watch` step that will automatically recompile via `gulp compile` on change
3. (noce to have) expose this stuff in a reusable way for other eyeglass modules (eyeglass itself is a module and should probably set a good example)

**Comment by kaelig** [comment]
:+1: for Babel

**Comment by alanhogan** [comment]
I had a lot of success including Babel's polyfill to run eyeglass & broccoli-eyeglass & eyeglass-spriting in a node 0.10 environment (which doesn’t natively support ES6). I discuss this here: https://github.com/sass-eyeglass/eyeglass-spriting/pull/8

**Comment by JohnAlbin** [comment]
If eyeglass ditches Node.js 0.10 and 0.12 support, you can use much of ES6 without a transpiler. Node.js 0.12 goes into maintenance mode on April 1, 2016. https://github.com/nodejs/LTS
