### ISSUE TITLE
custom functions not working?

### ISSUE THREAD

**Issue by franzheidl** [sass-eyeglass/eyeglass#40]
Me and others can't get custom functions declared in eyeglass-exports.js to work in the context of .scss:

sass-eyeglass/eyeglass-sample#1

cc @ahmedelgabri

**Comment by ahmedelgabri** [comment]
Hi @franzheidl, I don't think this is the right place for this issue. Cause the eyeglass module itself works _example: [eyeglass-math](https://github.com/sass-eyeglass/eyeglass-math)_ 

This issue is related to [eyeglass-sample](https://github.com/sass-eyeglass/eyeglass-sample) so IMO it'll be nice if you close this issue and keep the discussion there.

**Comment by franzheidl** [comment]
Ok, thanks.
